<?php
require_once('./Services/UIComponent/Button/classes/class.ilLinkButton.php');

/**
 * Class xlelIconButton
 *
 * @author  Fabian Schmid <fs@studer-raimann.ch>
 * @version 1.0.0
 */
class xlelIconButton extends ilLinkButton {

	/**
	 * @var string
	 */
	protected $icon = '';


	/**
	 * @return xlelIconButton
	 */
	public static function getInstance() {
		return new self('icon');
	}


	public function render() {
		return parent::render(); // TODO: Change the autogenerated stub
	}


	/**
	 * Prepare caption for render
	 *
	 * @return string
	 */
	protected function renderCaption() {
		return '<span class="glyphicon glyphicon-' . $this->getIcon() . '" aria-hidden="true"></span>';
	}


	/**
	 * @return string
	 */
	public function getIcon() {
		return $this->icon;
	}


	/**
	 * @param string $icon
	 */
	public function setIcon($icon) {
		$this->icon = $icon;
	}
}

?>
